// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import "github.com/Rogercode97/scouter/internal/types"

type Call struct {
	ID         int    `json:"id"`
	CallerName string `json:"caller_name"`
	CalleeName string `json:"callee_name"`
	Path       string `json:"path"`
	Line       int    `json:"line"`
	CalleePath string `json:"callee_path"`
	LinkType   string `json:"link_type"`
	Indegree   int    `json:"indegree"`
	Body       string `json:"body"`
}

type FileIndex struct {
	Path      string `json:"path"`
	Mtime     int    `json:"mtime"`
	Hash      string `json:"hash"`
	AstJson   string `json:"ast_json"`
	Project   string `json:"project"`
	Freshness int    `json:"freshness"`
}

type Symbol struct {
	ID             int                    `json:"id"`
	Name           string                 `json:"name"`
	Type           string                 `json:"type"`
	PackagePath    string                 `json:"package_path"`
	ReceiverType   string                 `json:"receiver_type"`
	Signature      string                 `json:"signature"`
	Doc            string                 `json:"doc"`
	Path           string                 `json:"path"`
	StartByte      int                    `json:"start_byte"`
	EndByte        int                    `json:"end_byte"`
	StartLine      int                    `json:"start_line"`
	StartCol       int                    `json:"start_col"`
	EndLine        int                    `json:"end_line"`
	StructuralHash string                 `json:"structural_hash"`
	Indegree       int                    `json:"indegree"`
	Relevance      float64                `json:"relevance"`
	Pagerank       float64                `json:"pagerank"`
	ChurnScore     float64                `json:"churn_score"`
	RuntimeHits    int                    `json:"runtime_hits"`
	AiSummary      string                 `json:"ai_summary"`
	Metrics        *types.SemanticMetrics `json:"metrics,omitempty"`
}
