// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package store

import (
	"context"
	"database/sql"
)

const clearSymbols = `-- name: ClearSymbols :exec
DELETE FROM symbols WHERE path = ?
`

func (q *Queries) ClearSymbols(ctx context.Context, path string) error {
	_, err := q.db.ExecContext(ctx, clearSymbols, path)
	return err
}

const getCallees = `-- name: GetCallees :many
SELECT id, caller_name, callee_name, path, line, callee_path, link_type, indegree, body FROM calls
WHERE caller_name = ?
`

func (q *Queries) GetCallees(ctx context.Context, callerName string) ([]Call, error) {
	rows, err := q.db.QueryContext(ctx, getCallees, callerName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.CallerName,
			&i.CalleeName,
			&i.Path,
			&i.Line,
			&i.CalleePath,
			&i.LinkType,
			&i.Indegree,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCallers = `-- name: GetCallers :many
SELECT id, caller_name, callee_name, path, line, callee_path, link_type, indegree, body FROM calls
WHERE callee_name = ?
LIMIT ? OFFSET ?
`

type GetCallersParams struct {
	CalleeName string `json:"callee_name"`
	Limit      int64  `json:"limit"`
	Offset     int64  `json:"offset"`
}

func (q *Queries) GetCallers(ctx context.Context, arg GetCallersParams) ([]Call, error) {
	rows, err := q.db.QueryContext(ctx, getCallers, arg.CalleeName, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Call
	for rows.Next() {
		var i Call
		if err := rows.Scan(
			&i.ID,
			&i.CallerName,
			&i.CalleeName,
			&i.Path,
			&i.Line,
			&i.CalleePath,
			&i.LinkType,
			&i.Indegree,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveCall = `-- name: SaveCall :exec
INSERT INTO calls (
    caller_name, callee_name, path, line, callee_path, link_type, indegree, body
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?
)
`

type SaveCallParams struct {
	CallerName string `json:"caller_name"`
	CalleeName string `json:"callee_name"`
	Path       string `json:"path"`
	Line       int    `json:"line"`
	CalleePath string `json:"callee_path"`
	LinkType   string `json:"link_type"`
	Indegree   int    `json:"indegree"`
	Body       string `json:"body"`
}

func (q *Queries) SaveCall(ctx context.Context, arg SaveCallParams) error {
	_, err := q.db.ExecContext(ctx, saveCall,
		arg.CallerName,
		arg.CalleeName,
		arg.Path,
		arg.Line,
		arg.CalleePath,
		arg.LinkType,
		arg.Indegree,
		arg.Body,
	)
	return err
}

const saveFileIndex = `-- name: SaveFileIndex :exec
INSERT INTO file_index (
    path, mtime, hash, ast_json, project, freshness
) VALUES (
    ?, ?, ?, ?, ?, ?
)
ON CONFLICT(path) DO UPDATE SET
    mtime = excluded.mtime,
    hash = excluded.hash,
    ast_json = excluded.ast_json,
    project = excluded.project,
    freshness = excluded.freshness
`

type SaveFileIndexParams struct {
	Path      string `json:"path"`
	Mtime     int    `json:"mtime"`
	Hash      string `json:"hash"`
	AstJson   string `json:"ast_json"`
	Project   string `json:"project"`
	Freshness int    `json:"freshness"`
}

func (q *Queries) SaveFileIndex(ctx context.Context, arg SaveFileIndexParams) error {
	_, err := q.db.ExecContext(ctx, saveFileIndex,
		arg.Path,
		arg.Mtime,
		arg.Hash,
		arg.AstJson,
		arg.Project,
		arg.Freshness,
	)
	return err
}

const saveSymbol = `-- name: SaveSymbol :exec
INSERT INTO symbols (
    name, type, package_path, receiver_type, signature, doc,
    path, start_byte, end_byte, start_line, start_col, end_line,
    structural_hash, indegree, relevance, pagerank, churn_score,
    runtime_hits, ai_summary
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
`

type SaveSymbolParams struct {
	Name           string  `json:"name"`
	Type           string  `json:"type"`
	PackagePath    string  `json:"package_path"`
	ReceiverType   string  `json:"receiver_type"`
	Signature      string  `json:"signature"`
	Doc            string  `json:"doc"`
	Path           string  `json:"path"`
	StartByte      int     `json:"start_byte"`
	EndByte        int     `json:"end_byte"`
	StartLine      int     `json:"start_line"`
	StartCol       int     `json:"start_col"`
	EndLine        int     `json:"end_line"`
	StructuralHash string  `json:"structural_hash"`
	Indegree       int     `json:"indegree"`
	Relevance      float64 `json:"relevance"`
	Pagerank       float64 `json:"pagerank"`
	ChurnScore     float64 `json:"churn_score"`
	RuntimeHits    int     `json:"runtime_hits"`
	AiSummary      string  `json:"ai_summary"`
}

func (q *Queries) SaveSymbol(ctx context.Context, arg SaveSymbolParams) error {
	_, err := q.db.ExecContext(ctx, saveSymbol,
		arg.Name,
		arg.Type,
		arg.PackagePath,
		arg.ReceiverType,
		arg.Signature,
		arg.Doc,
		arg.Path,
		arg.StartByte,
		arg.EndByte,
		arg.StartLine,
		arg.StartCol,
		arg.EndLine,
		arg.StructuralHash,
		arg.Indegree,
		arg.Relevance,
		arg.Pagerank,
		arg.ChurnScore,
		arg.RuntimeHits,
		arg.AiSummary,
	)
	return err
}

const searchSymbols = `-- name: SearchSymbols :many
SELECT id, name, type, package_path, receiver_type, signature, doc, path, start_byte, end_byte, start_line, start_col, end_line, structural_hash, indegree, relevance, pagerank, churn_score, runtime_hits, ai_summary FROM symbols
WHERE name LIKE '%' || ? || '%' OR signature LIKE '%' || ? || '%'
LIMIT ? OFFSET ?
`

type SearchSymbolsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
	Offset  int64          `json:"offset"`
}

func (q *Queries) SearchSymbols(ctx context.Context, arg SearchSymbolsParams) ([]Symbol, error) {
	rows, err := q.db.QueryContext(ctx, searchSymbols,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Symbol
	for rows.Next() {
		var i Symbol
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.PackagePath,
			&i.ReceiverType,
			&i.Signature,
			&i.Doc,
			&i.Path,
			&i.StartByte,
			&i.EndByte,
			&i.StartLine,
			&i.StartCol,
			&i.EndLine,
			&i.StructuralHash,
			&i.Indegree,
			&i.Relevance,
			&i.Pagerank,
			&i.ChurnScore,
			&i.RuntimeHits,
			&i.AiSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
